from docx import Document
from docx.shared import Pt, Inches, RGBColor
import os

output_path = os.path.join(os.path.expanduser("~"), "Desktop", "Library_Management_System_Project.docx")
doc = Document(output_path)

def h1(t): doc.add_heading(t, level=1)
def h2(t): doc.add_heading(t, level=2)
def h3(t): doc.add_heading(t, level=3)
def p(t, bold=False):
    para = doc.add_paragraph()
    run = para.add_run(t)
    run.bold = bold
def bullet(t): doc.add_paragraph(t, style='List Bullet')
def numbered(t): doc.add_paragraph(t, style='List Number')
def pb(): doc.add_page_break()

# ============ CHAPTER 1 ============
pb()
h1("CHAPTER ONE: INTRODUCTION")

h2("1.1 Background of the Study")
p("Libraries play an important role in supporting teaching, learning, research, and access to information in educational institutions. They provide students, lecturers, researchers, and other users with access to books and other learning resources. As the number of library resources and users increases, effective management of library activities becomes increasingly important.")
p("Traditionally, many libraries have relied on manual methods for managing books, members, borrowing, and returning activities. These methods may involve the use of paper records, registers, or spreadsheets. Although such approaches can be used for small collections, they can become time-consuming and difficult to manage when the number of books and library users increases.")
p("The development of information and communication technologies has provided opportunities for libraries to automate many of these activities. A Library Management System is a software application designed to support the management of library resources and services through computerized processes.")
p("The proposed Library Management System is a web-based application developed using Flask, a Python web framework, and MySQL as the database management system. The system provides a centralized platform for managing books, library members, and borrowing transactions.")
p("The system is intended to provide a simple, accessible, and efficient approach to library management. By automating major library operations, the system can assist library personnel in maintaining organized records, monitoring book availability, and retrieving information more efficiently.")

h2("1.2 Problem Statement")
p("Effective management of library resources requires accurate and timely information about books, members, and borrowing transactions. In many library environments, these activities may be handled using manual records or separate record-keeping methods.")
p("One of the problems addressed by this project is the difficulty of maintaining accurate book records and monitoring book availability. When information about books and quantities is maintained manually, it may be difficult to determine the number of copies currently available.")
p("Another problem is the inefficient management of library members. Manual registration can result in incomplete, inconsistent, or duplicate member records.")
p("The management of book borrowing and returning transactions is another challenge. Without a centralized system, it can be difficult to keep track of which member has borrowed a particular book.")
p("These challenges demonstrate the need for a centralized computerized solution that can integrate the major activities involved in library management. Therefore, this project develops a web-based Library Management System using Flask and MySQL.")

h2("1.3 Main Objective")
p("The main objective of this project is to develop and implement a web-based Library Management System that automates the management of library books, members, borrowing and returning transactions, and book inventory, while providing secure access to authorized library personnel.")

h2("1.4 Specific Objectives")
numbered("To design and develop a centralized database for storing and managing library information.")
numbered("To develop a secure user authentication and access mechanism for authorized library personnel.")
numbered("To develop book and member management modules that prevent duplicate registrations.")
numbered("To develop borrowing and returning modules with automatic stock updates, overdue management, and fine calculation.")
numbered("To implement dashboard, reporting, analytics, and low-stock monitoring features, and to test the system against its functional requirements.")

h2("1.5 Research Questions")
numbered("How can a centralized database be designed to manage library books, members, users, and borrowing transactions?")
numbered("How can secure user authentication and access control be implemented?")
numbered("How can computerized book and member management modules improve library operations while preventing duplicate records?")
numbered("How can borrowing and returning processes be automated to support overdue and fine management?")
numbered("To what extent does the developed system satisfy its functional requirements?")

h2("1.6 Significance of the Study")
p("The system is expected to benefit library personnel, library members, the institution, system administrators, future researchers, and the researcher.")
h3("1.6.1 Library Personnel")
p("The system will assist library personnel in managing daily library activities more efficiently.")
h3("1.6.2 Library Members")
p("Library members will benefit from more organized and efficient library services.")
h3("1.6.3 The Institution")
p("The institution will benefit from improved organization and management of library information.")
h3("1.6.4 Future Researchers")
p("The project will provide a useful reference for students, researchers, and developers.")

h2("1.7 Scope of the Study")
p("The study focuses on the design, development, implementation, testing, and deployment of a web-based Library Management System using Flask and MySQL.")
p("The scope covers user authentication, book management, member management, borrowing and returning, overdue and fine management, dashboard, reports, analytics, search, user profile, database management, and web deployment.")

h2("1.8 Limitations of the Study")
p("The study had the following limitations:")
bullet("Internet and network dependency")
bullet("System availability depends on hosting services")
bullet("Data accuracy depends on user input")
bullet("User training may be required")
bullet("Security limitations inherent in any software system")
bullet("Integration with external systems may require additional development")
bullet("Advanced notification services not implemented")
bullet("Performance depends on hardware and infrastructure")

h2("1.9 Definition of Terms")
p("Analytics: The process of examining and interpreting library data.")
p("Authentication: The process of verifying user identity.")
p("Book Availability: The number of copies available for borrowing.")
p("Borrowing Transaction: A recorded activity where a member is issued a book.")
p("Dashboard: A graphical interface displaying library statistics.")
p("Database: An organized collection of data stored electronically.")
p("Fine: A monetary amount for failing to return a book on time.")
p("Flask: A Python web framework.")
p("Library Management System: A computerized system for managing library resources.")
p("Member: A registered library user authorized to borrow books.")
p("MySQL: A relational database management system.")
p("Overdue Book: A borrowed book not returned by the due date.")
p("Web-Based System: A software application accessed through a web browser.")

# ============ CHAPTER 2 ============
pb()
h1("CHAPTER TWO: LITERATURE REVIEW")

h2("2.1 Introduction")
p("This chapter presents a review of literature related to Library Management Systems and the use of information technology in the management of library resources and services.")

h2("2.2 Concept of Library Management Systems")
p("A Library Management System (LMS) is a computerized information system designed to support the organization, management, and monitoring of library resources and services.")
p("The primary purpose of a Library Management System is to automate activities that may otherwise require manual record keeping. These activities commonly include registering library members, recording books, monitoring book availability, processing borrowing and returning transactions, and maintaining transaction histories.")

h2("2.3 Computerized Library Management Systems")
p("Computerized Library Management Systems use information and communication technologies to automate the management of library resources, users, and transactions.")
p("A major advantage of computerized library management is centralized data management. Computerized systems improve book and inventory management by maintaining up-to-date information about library resources.")

h2("2.4 Review of Existing Library Management Systems")
p("This section reviews three established systems: Koha, Evergreen, and Senayan Library Management System (SLiMS).")
h3("2.4.1 Koha Library Management System")
p("Koha is an open-source library automation system that is used by libraries of different sizes. The system provides functionality for acquisitions, circulation, cataloguing, serials management, authorities, reporting, label printing, notifications, and offline circulation.")
h3("2.4.2 Evergreen Integrated Library System")
p("Evergreen is another open-source Integrated Library System designed to support library operations. Its documentation describes functionality for catalog searching, circulation, holds, reservations, patron accounts, and other library activities.")
h3("2.4.3 Senayan Library Management System (SLiMS)")
p("Senayan Library Management System (SLiMS) is an open-source Library Management System that provides functionality intended to assist libraries and librarians in managing library resources.")
h3("2.4.4 Comparative Review of Existing Systems")
p("The reviewed systems demonstrate that modern Library Management Systems can provide significantly more functionality than traditional manual methods.")

h2("2.5 Technologies Used in Library Management Systems")
p("The development of a modern Library Management System requires a combination of programming languages, web technologies, database technologies, and development tools.")
h3("2.5.1 Python")
p("Python is a high-level programming language used as the main programming language for the development of the proposed Library Management System.")
h3("2.5.2 Flask")
p("Flask is a Python web framework used to develop the server-side component of the Library Management System.")
h3("2.5.3 MySQL")
p("MySQL is a relational database management system used to store and manage the data generated by the Library Management System.")
h3("2.5.4 HTML, CSS, Bootstrap, and JavaScript")
p("HTML provides structure, CSS provides styling, Bootstrap provides responsive design, and JavaScript provides interactivity for the web interface.")

h2("2.6 Key Features of Modern Library Management Systems")
p("The following are key features of modern Library Management Systems:")
bullet("User Authentication and Access Control")
bullet("Book Management")
bullet("Member Management")
bullet("Borrowing and Returning")
bullet("Overdue Management")
bullet("Fine Management")
bullet("Inventory and Stock Management")
bullet("Search and Book Suggestions")
bullet("Borrowing History")
bullet("Reports")
bullet("Analytics and Statistics")
bullet("Dashboard")
bullet("User Profile Management")
bullet("Web-Based Access")

h2("2.7 Research Gap")
p("The review of existing literature and library management systems shows that information technology has significantly improved the management of library resources and services.")
p("However, many existing library management systems are designed as comprehensive solutions. For a smaller institution or a specific academic environment, there is a need for a focused system that provides the essential functions required by its library personnel while maintaining a simple and manageable interface.")
p("Therefore, the research gap identified in this study is the need for a focused, integrated, and context-appropriate web-based Library Management System.")

h2("2.8 Conceptual Framework")
p("The framework is based on three main components: Input, Process, and Output.")
h3("2.8.1 Input")
p("The input component consists of book information, member information, user information, borrowing information, returning information, overdue and fine information, and search information.")
h3("2.8.2 Process")
p("The process component includes authentication, book management, member management, borrowing and returning, automatic stock updates, overdue detection, fine calculation, low-stock monitoring, transaction tracking, reporting, analytics, and dashboard processing.")
h3("2.8.3 Output")
p("The output component includes updated library records, book availability information, borrowing/returning history, overdue records, fine information, low-stock alerts, reports, analytics, dashboard statistics, and search results.")
h3("2.8.4 Conceptual Framework Model")
p("INPUT -> PROCESS -> OUTPUT")
p("The conceptual framework demonstrates that the Library Management System transforms raw library data into organized and useful information through automated processing.")

h2("2.9 Summary")
p("This chapter reviewed literature related to Library Management Systems. The chapter examined the concept of Library Management Systems, computerized library management systems, existing systems (Koha, Evergreen, and SLiMS), technologies used, and key features of modern Library Management Systems.")

# ============ CHAPTER 3 ============
pb()
h1("CHAPTER THREE: METHODOLOGY")

h2("3.1 Introduction")
p("This chapter describes the methodology used in the analysis, design, development, implementation, and testing of the proposed Web-Based Library Management System.")

h2("3.2 Research Design")
p("Research design refers to the overall plan and structure used to guide the collection, analysis, and interpretation of information required for a study. For this project, a descriptive research design was adopted.")
p("The descriptive design was appropriate because the project required an understanding of how library activities such as book registration, member registration, borrowing, returning, inventory monitoring, overdue management, fine tracking, and report preparation are performed.")

h2("3.3 System Development Methodology")
p("The Agile software development methodology was adopted for the development of the Web-Based Library Management System.")
p("Instead of developing the entire system as one large component, the system was divided into smaller modules. Each module was developed, tested, reviewed, and improved before being integrated with other modules.")
h3("3.3.1 Requirements Identification")
p("The first stage involved identifying the requirements of the Library Management System.")
h3("3.3.2 System Planning and Design")
p("After identifying the requirements, the system structure was planned. The database entities, relationships, system modules, and user interfaces were designed.")
h3("3.3.3 Incremental Development")
p("The system was developed module by module, including authentication, dashboard, book management, member management, borrowing, returning, stock updates, overdue detection, fine management, low-stock monitoring, reports, analytics, and user profile.")
h3("3.3.4 Testing and Debugging")
p("Each developed module was tested to verify that it performed the intended function.")
h3("3.3.5 Integration")
p("After individual modules were developed and tested, they were integrated into the complete Library Management System.")

h2("3.4 Requirements Gathering")
p("Requirements gathering is the process of identifying and documenting the functions, services, constraints, and expectations that a system must satisfy.")
h3("3.4.1 Observation")
p("Observation was used to understand the activities involved in managing library resources and services.")
h3("3.4.2 Interviews and Discussions")
p("Informal interviews and discussions were used to obtain information about the requirements of library personnel.")
h3("3.4.3 Document and Record Review")
p("Existing library records and documentation were considered to understand the type of information normally required during library operations.")
h3("3.4.4 System Requirements Analysis")
p("The information gathered was analyzed to identify the major requirements of the proposed system.")
h3("3.4.5 Validation of Requirements")
p("The identified requirements were reviewed during the design and development stages.")

h2("3.5 Data Collection Methods")
p("Data collection involved obtaining relevant information required to understand library management activities.")
h3("3.5.1 Observation")
p("Observation was used to examine the activities involved in library management.")
h3("3.5.2 Interviews")
p("Interviews were used to obtain information from individuals involved in library operations.")
h3("3.5.3 Document and Record Review")
p("Existing library records and documents were reviewed.")
h3("3.5.4 Literature Review")
p("Relevant books, academic materials, technical documentation, and existing Library Management Systems were reviewed.")
h3("3.5.5 Online and Technical Resources")
p("Online technical resources and official documentation were consulted during the development of the system.")

h2("3.6 System Development Tools and Technologies")
p("The development of the Web-Based Library Management System involved the use of various programming languages, frameworks, database technologies, web development technologies, and development tools.")
h3("3.6.1 Python")
p("Python was used as the main programming language for developing the application logic.")
h3("3.6.2 Flask")
p("Flask was used as the web application framework for developing the backend.")
h3("3.6.3 MySQL")
p("MySQL was used as the relational database management system.")
h3("3.6.4 MySQL Connector/Python")
p("MySQL Connector/Python was used to establish communication between the Python/Flask application and the MySQL database.")
h3("3.6.5 HTML and CSS")
p("HTML was used to structure the web pages, while CSS was used to control the visual appearance.")
h3("3.6.6 Bootstrap")
p("Bootstrap was used to enhance the user interface and provide responsive web page layouts.")
h3("3.6.7 JavaScript")
p("JavaScript was used to provide interactive functionality on the client side.")
h3("3.6.8 MySQL Workbench")
p("MySQL Workbench was used as a database development and management tool.")
h3("3.6.9 Cloud Hosting and Deployment")
p("Cloud hosting was used to make the Library Management System accessible through the web.")

h2("3.7 Ethical and Security Considerations")
p("Ethical and security considerations were incorporated into the development of the Web-Based Library Management System.")
h3("3.7.1 Data Privacy and Confidentiality")
p("Access to protected system functions is restricted through user authentication and sessions.")
h3("3.7.2 Authentication and Access Control")
p("Authentication was implemented to restrict access to protected functions.")
h3("3.7.3 Data Integrity")
p("Data integrity was considered through both database design and application validation.")
h3("3.7.4 Input Validation")
p("Input validation was implemented to reduce invalid or incomplete information being processed.")
h3("3.7.5 Security Limitations and Future Improvements")
p("Future improvements are recommended for stronger password hashing, role-based permissions, audit logging, automated backups, and security monitoring.")

h2("3.8 Chapter Summary")
p("This chapter presented the methodology followed in the development of the Web-Based Library Management System. It described the research design, Agile development approach, requirements gathering methods, data collection methods, and the tools and technologies used.")

doc.save(output_path)
print("PART 2 DONE - Chapters 1, 2, 3 saved successfully!")